type UserNotFound* = ref object of CatchableError
